#!/bin/bash
#

REPLY=""

function checkpatch() {
	PDIR=$1
	sed -i "/^Issue:[ 0-9]*/Id" $PDIR/*.patch
	sed -i "/^Change-id:[ 0-9]*/Id" $PDIR/*.patch

	if [ -e "scripts/checkpatch.pl" ]; then
		# We are in kernel repo
		IN_TREE=""
	else
		IN_TREE="--no-tree --ignore PREFER_KERNEL_TYPES,FILE_PATH_CHANGES,EXECUTE_PERMISSIONS"
	fi

	for file in $PDIR/*.patch; do
		[ -e "$file" ] || continue
		[ "$file" != "$PDIR/0000-cover-letter.patch" ] || continue
		perl $CHECKPATCH $IN_TREE --strict -q $file
	done
}

function check_ssh_access() {
	local ADDR=$1
	set +e
	ssh -q -o ConnectTimeout=2 $ADDR exit
	local SSH_READY=$?
	set -e
	REPLY=$SSH_READY
}

function numb_of_cpus() {
	REPLY=$( lscpu | grep "CPU(s): " | head -n 1 | awk '{print $2}' )
}

function get_passthrough_line() {
	VM_MACHINE=$1
	REPLY=$(grep $VM_MACHINE $DIR/machines.db | awk '{print " -device vfio-pci,host="$2} ' | tr -d '\n' )
}

function mass_vfio_bind() {
	VM_MACHINE=$1
	echo "Binding devices, it takes time ...."
	REPLY=$(grep $VM_MACHINE $DIR/machines.db | awk '{print $2} ' | xargs -n1 sudo $DIR/vfio-pci-bind )
}
