#!/bin/bash
#
# Run various static checkers on one specific commit
#  * sparse
#  * smatch
#  # checkpatch

if [ "$#" -gt 1 ]; then
        echo "Usage: x checks <commit sha1>"
        exit 1
fi

. $HOME/.x-tools

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common

if [ "$#" -gt 0 ]; then
	SHA1=$1
else
	SHA1="HEAD"
fi

REPORT_FILE=$(mktemp)

numb_of_cpus
NUMB_OF_CPUS=$REPLY

function do_one {
	SHA1=$1
	REPORT_FILE=$2
	PDIR=$(mktemp -d)

	git worktree add $PDIR $SHA1
	echo "Redirecting the output to $REPORT_FILE"
	pushd $PDIR &>> $REPORT_FILE
	VER=$( less $KCONFIG | head -n 3 | tail -n 1 )
	echo $VER &>> $REPORT_FILE
	echo "========================================" &>> $REPORT_FILE

	x checkpatch HEAD $PDIR &>> $REPORT_FILE
	echo "===== ALL MOD COMPILE (subdir) =========" &>> $REPORT_FILE
	make allmodconfig &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE
	echo "===== ALL YES COMPILE (subdir) =========" &>> $REPORT_FILE
	make allyesconfig &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE
	echo "===== ALL NO COMPILE (subdir) =========" &>> $REPORT_FILE
	make allnoconfig &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE

	make clean -j $NUMB_OF_CPUS &>> /dev/null
	cp $KCONFIG .config &>> $REPORT_FILE
	make olddefconfig &>> $REPORT_FILE

	echo "===== FULL COMPILE =========" &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS &>> $REPORT_FILE

	# Checkers runs with allyes in clean env
	make clean -j $NUMB_OF_CPUS &>> /dev/null
	make allyesconfig &>> /dev/null
	# CLOSED, too many warnings
	#echo "===== SUB COMPILE =========" &>> $REPORT_FILE
	#make -s -j $NUMB_OF_CPUS W=1 drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE
	echo "===== SMATCH =========" &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS CHECK="$SMATCH -p=kernel" C=1 drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE
	make clean -j $NUMB_OF_CPUS &>> /dev/null
	make allyesconfig &>> /dev/null
	echo "===== SPARSE =========" &>> $REPORT_FILE
	make -s -j $NUMB_OF_CPUS CHECK="$SPARSE" C=2 drivers/infiniband/ drivers/net/ethernet/mellanox/ &>> $REPORT_FILE

	popd &>> $REPORT_FILE

	# TODO: separate checkpatch errors, sparse, smatch
	#NUMB_OF_ERRORS=$(grep "[0-9]: " $REPORT_FILE | sort | uniq |wc -l)
	NUMB_OF_ERRORS=$(awk -F": " '{print $1}' $REPORT_FILE | grep ":" | sort | uniq |wc -l)
	LAST_NUMB_OF_ERRORS=$(head -1 $CHECKS_LOG | awk '{print $1}')
	DELTA=$((LAST_NUMB_OF_ERRORS-NUMB_OF_ERRORS))

	echo "There are $NUMB_OF_ERRORS errors/warnings, delta: $DELTA."
	tac $CHECKS_LOG > $PDIR/x-checks.tac
	echo "$NUMB_OF_ERRORS $DELTA $(git log --abbrev=12 -1 --format='%h "%s"')" >> $PDIR/x-checks.tac
	tac $PDIR/x-checks.tac > $CHECKS_LOG
	rm -rf $PDIR
	git worktree prune
}

do_one $SHA1 $REPORT_FILE
