#!/bin/bash
#
# Run full CI for specific commit

if [ "$#" -gt 1 ]; then
        echo "Usage: x ci <commit sha1>"
        exit 1
fi

. $HOME/.x-tools

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common


# Allow to run without parameters from any place
SHA1="HEAD"
#if [ "$#" -gt 0 ]; then
#	SHA1=$1
#else
#	SHA1=$(git rev-parse HEAD)
#fi

REPORT_FILE=$(mktemp)

function do_one {
	local SHA1=$1
	local VM=$2
	x run $VM &
	sleep 1m
	block_till_ssh_is_ready $VM
	set +e
	ssh root@$VM /images/ci/shutdown
	set -e
	wait
}

do_one $SHA1 nps-server-14-015
do_one $SHA1 nps-server-14-017
do_one $SHA1 nps-server-14-016
do_one $SHA1 nps-server-14-018
do_one $SHA1 nps-server-14-019
do_one $SHA1 nps-server-14-020
#wait
