#!/bin/bash
#
# Clean specific commit from gerrit junk

if [ "$#" -gt 1 ]; then
        echo "Usage: x clean <commit sha1>"
        exit 1
fi

. $HOME/.x-tools

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common

if [ "$#" -gt 0 ]; then
	IN=$1
else
	IN="HEAD"
fi

PREV=$IN^1

set -e
PRTMP=$(mktemp -d)
git format-patch -M -C --no-cover-letter -s -o $PRTMP/ $PREV

sed -i "/^Issue:[ 0-9]*/Id" $PRTMP/0001-*.patch
sed -i "/^Change-id:[ 0-9]*/Id" $PRTMP/0001-*.patch

git reset --hard $PREV
git am $PRTMP/*

rm -rf $PRTMP
