#!/bin/bash
#
# Run virt image

if [ "$#" -ne 1 ]; then
        echo "Usage: x run <name>"
        exit 1
fi

. $HOME/.x-tools

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common

USER=$(whoami)
if [ "$USER" == "root" ]; then
	echo "Please don't run this script as root, exiting ..."
	exit
fi

VNAME=$1

if [ ! -f "$X_BI_DIR/$VNAME.img" ]; then
	echo "$X_BI_DIR/$VNAME.img doesn't exist, exiting ...."
	exit
fi

DHCP_FILE=/.autodirect/LIT/SCRIPTS/DHCPD/list.html
MAC=""

if [ -f $DHCP_FILE ]; then
	# We are running in MLNX network
	MAC=`grep $VNAME $DHCP_FILE | cut -d";" -f2 | tr -d " "`
	if [ "$MAC" == "" ]; then
		echo "Didn't find $VNAME MAC in $DHCP_FILE"
	fi
fi

if [ "$MAC" == "" ]; then
	# Random generate
	printf -v MAC "52:54:%02x:%02x:%02x:%02x" $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff ))
fi

mass_vfio_bind $VNAME
get_passthrough_line $VNAME
PCI_IDS_PASS=$REPLY
qemu-system-x86_64 -enable-kvm \
	-machine accel=kvm:tcg -cpu host -smp cpus=2 \
	-m 8096 -drive file=$X_BI_DIR/$VNAME.img,format=raw,if=virtio \
	-no-reboot -nographic -net bridge,br=br0 \
	-net nic,model=virtio,macaddr=$MAC $PCI_IDS_PASS \
	-virtfs local,path=$X_BI_MOUNT,mount_tag=host0,security_model=mapped,id=host0 \
	-kernel $X_SRC/kernel/arch/x86/boot/bzImage \
	-append 'root=/dev/vda4 earlyprintk=serial,ttyS0,115200 console=tty0 console=ttyS0,115200 debug rw systemd.show_status=0 printk.devkmsg=off rootfstype=xfs audit=0'
