#!/bin/bash
#
# Mark specific commit as targeted for stable

if [ "$#" -gt 1 ]; then
        echo "Usage: x stable <commit sha1>"
        exit 1
fi

. $HOME/.x-tools

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/common

if [ "$#" -gt 0 ]; then
	IN=$1
else
	IN="HEAD"
fi

PREV=$IN^1

set -e
FIXES=$(git show $IN | grep Fixes | awk '{print $2}')

get_project $PWD
PROJECT=$REPLY

if [ "$PROJECT" == "kernel" ]; then
	if [ "$(git show $IN | grep -c stable\@vger.kernel.org)" -gt 0 ]; then
		echo "There is already stable@vger.kernel.org in the commit message. Exiting..."
		exit
	fi
	# We are in kernel repo
	TAG=$(git l --author="Linus Torvalds" --no-merges $FIXES..HEAD | grep Linux | awk '{print $3}' | tail -1 | cut -d'-' -f1)
	STABLE="Cc: <stable@vger.kernel.org> # $TAG"
fi

if [ "$PROJECT" == "rdma-core" ]; then
	if [ "$(git show $IN | grep -c stable\@linux-rdma.org)" -gt 0 ]; then
		echo "There is already stable@linux-rdma.org in the commit message. Exiting..."
		exit
	fi
	STABLE="Cc: <stable@linux-rdma.org>"
fi

PRTMP=$(mktemp -d)
git format-patch -M -C --no-cover-letter -s -o $PRTMP/ $PREV

sed -i "/Fixes: /i $STABLE" $PRTMP/0001-*

git reset --hard $PREV
git am $PRTMP/*

rm -rf $PRTMP
